### ISSUE TITLE
Support for Django-1.10

### ISSUE THREAD

**Issue by divick** [applecat/django-simple-poll#14]
This does not work for Django-1.10 and complains with the following message:

```
  File "/home/ubuntu/Env/oba/local/lib/python2.7/site-packages/poll/urls.py", line 4, in <module>
    from django.conf.urls.defaults import patterns, url
ImportError: No module named defaults

```
Deprecated and removed names from Django-1.10 are to be removed from this app to for it to work properly.

**Comment by applecat** [comment]
Please update to version to v0.2.1 — everything should be ok.

**Comment by divick** [comment]
Thanks for fixing it.
