### ISSUE TITLE
2 polls on page

### ISSUE THREAD

**Issue by andrewt82** [applecat/django-simple-poll#15]
Hello!
when i add more of 1 polls, on site show only 1 poll, how fix it?

template tags like
{% poll 1 %}
{% poll 2 %}

don't work

how show 2 or more polls on page?

**Comment by applecat** [comment]
@andrewt82, there is no such functional now in django-simple-poll. You can only view latest poll with {% poll %} template tag as we can see in this code (file `templatetags/poll_tags.py`):
```python
    try:
        poll = Poll.published.latest("date")
    except Poll.DoesNotExists:
        return ''
```


But I think you can simply extend this behavior by passing `id` param into templatetag like this:

```python
@register.simple_tag(takes_context=True)
def poll(context, id=None):
    request = context['request']
        
    try:
        if id:
            poll = Poll.published.get(id=id)
        else:
            poll = Poll.published.latest("date")
    except Poll.DoesNotExists:
        return ''

    ...
```

Tell me if this works for you and I can update the code and release version.
