### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Logmytech** [applecat/django-simple-poll#16]
I'm contributing to a reddit and forum clone called Djeddit. https://github.com/EatEmAll/django-djeddit/

I'm planning of implementing polls for the posts like in a forum, but I want it inbuilt into Djeddit.

It has no license, so I can assume it's public domain.

Can I copy code in this project and paste and use it in that project.

Is this project public domain?

**Comment by applecat** [comment]
@Logmytech of course, you can copy this code and paste in Djeddit.
django-simple-poll is public domain.

**Comment by applecat** [comment]
LICENSE added to project.
